version: '2.4'
services:
  
  postgres-db:
    image: tiredofit/postgres:13
    container_name: postgres-db  
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - CONTAINER_NAME=postgres-db
    networks:
      - services
    restart: always

networks:
  internal:
    external: false
